---
title: "Data processing and sampling"
subtitle: "EuroCSS workshop: LTTA"
output: html_notebook
author:  B Kleinberg https://github.com/ben-aaron188
---


## Preparation

```{r}
#clear R workspace
rm(list = ls())
```



```{r}
#load deps
require(tm)
require(data.table)
require(splitstackshape)
```


```{r}
#set directroy for this session
setwd('/Users/bennettkleinberg/GitHub/ltta_workshop_data')
```


```{r}
#load source function
source('./r_deps/txt_df_from_dir.R')
```
*Note: this code lives [here](https://github.com/ben-aaron188/r_helper_functions/blob/master/txt_df_from_dir.R)*

## Read individual files into dataframes
This is done separately for left and right

```{r}
t1 = Sys.time()
df.full_corpus = txt_df_from_dir(dirpath = './'
                                 , recursive = T
                                 , to_lower = F
                                 , include_processed = F)
t2 = Sys.time()
t2-t1
```

```{r}
#set variable for merge with meta data
df.full_corpus$vlog_id = sub('(.*)\\..*','\\1', df.full_corpus$file_id)
df.full_corpus$channel_vlog_id = tolower(paste(df.full_corpus$file_parent, df.full_corpus$vlog_id, sep="_"))

df.full_corpus = df.full_corpus[nchar(df.full_corpus$text) > 0, ]
df.full_corpus = droplevels(df.full_corpus)

nrow(df.full_corpus)

```

### Load meta file & merge
```{r}
df.meta = as.data.frame(fread('../../../overview_left.txt'
                              , sep = ","
                              , header=F))

#set names
names(df.meta) = c('channel_id'
                   , 'file_id'
                   , 'url'
                   , 'view_count'
                   , 'date_posted'
                   , 'landing_url'
                   , 'upvotes'
                   , 'downvotes')

#set variables to correct format
df.meta$channel_id = sub('(.*)\\..*','\\1', df.meta$channel_id)
df.meta$channel_vlog_id = tolower(paste(df.meta$channel_id, df.meta$file_id, sep="_"))
df.meta$view_count = as.numeric(gsub("[.]", "", as.character(df.meta$view_count)))
df.meta$upvotes = as.numeric(gsub("[.]", "", as.character(df.meta$upvotes)))
df.meta$downvotes = as.numeric(gsub("[.]", "", as.character(df.meta$downvotes)))
df.meta$date_posted = as.Date(df.meta$date_posted)
reference_date = as.Date('2018-10-30')
df.meta$days_until_reference = as.numeric(reference_date - df.meta$date_posted)
df.meta$view_count_corrected = round(df.meta$view_count/df.meta$days_until_reference, 2)
df.meta = na.omit(df.meta)

#merge files with meta file
df.data_left = merge(df.full_corpus, df.meta, by='channel_vlog_id', all.x = T)
df.data_left = na.omit(df.data_left)
df.data_left$pol = 'l'
```


## Same procedure for 'right' videos

```{r}
#set working directory
setwd('../../right/parsed/')
```

## Load data

```{r}
t1 = Sys.time()
df.full_corpus = txt_df_from_dir(dirpath = './'
                                 , recursive = T
                                 , to_lower = F
                                 , include_processed = F)
t2 = Sys.time()
t2-t1
```

```{r}
#set variable for merge with meta data
df.full_corpus$vlog_id = sub('(.*)\\..*','\\1', df.full_corpus$file_id)
df.full_corpus$channel_vlog_id = tolower(paste(df.full_corpus$file_parent, df.full_corpus$vlog_id, sep="_"))

df.full_corpus = df.full_corpus[nchar(df.full_corpus$text) > 0, ]
df.full_corpus = droplevels(df.full_corpus)

nrow(df.full_corpus)
```

### Load meta file & merge
```{r}
df.meta = as.data.frame(fread('../../../overview_right.txt'
                              , sep = ","
                              , header=F))

#set names
names(df.meta) = c('channel_id'
                   , 'file_id'
                   , 'url'
                   , 'view_count'
                   , 'date_posted'
                   , 'landing_url'
                   , 'upvotes'
                   , 'downvotes')

#set variables to correct format
df.meta$channel_id = sub('(.*)\\..*','\\1', df.meta$channel_id)
df.meta$channel_vlog_id = tolower(paste(df.meta$channel_id, df.meta$file_id, sep="_"))
df.meta$view_count = as.numeric(gsub("[.]", "", as.character(df.meta$view_count)))
df.meta$upvotes = as.numeric(gsub("[.]", "", as.character(df.meta$upvotes)))
df.meta$downvotes = as.numeric(gsub("[.]", "", as.character(df.meta$downvotes)))
df.meta$date_posted = as.Date(df.meta$date_posted)
reference_date = as.Date('2018-10-30')
df.meta$days_until_reference = as.numeric(reference_date - df.meta$date_posted)
df.meta$view_count_corrected = round(df.meta$view_count/df.meta$days_until_reference, 2)
df.meta = na.omit(df.meta)

#merge files with meta file
df.data_right = merge(df.full_corpus, df.meta, by='channel_vlog_id', all.x = T)
df.data_right = na.omit(df.data_right)
df.data_right$pol = 'r'
```

### Bind `df.data_left` and `df.data_right`
Use the data.table format for faster processing

```{r}
df.data = rbind(df.data_left, df.data_right)
dt.data = setDT(df.data)

#store data (do not run)
# save(dt.data
#      , file='../../../eurocss_ltta_workshop_data.RData')
```

## Sampling

```{r}
table(dt.data$pol)
```

```{r}
#only channels with at least 2000 videos
selected_channels = dt.data[, .N, by=file_parent][N > 2000, file_parent]

dt.sub = dt.data[file_parent %in% selected_channels, ]
```

```{r}
set.seed(123)

#stratified sampling: 2000 rows controlled for file_paren (= channel)
dt.sampled = stratified(dt.sub, c("file_parent", "pol"), 2000)

#selected 4 channels from the 'left'
selected_channels_left = sample(x = unique(dt.sampled$file_parent[dt.sampled$pol == 'l'])
                                , size = 4
                                , replace = F
                                )

#sub-setting with final channels
final_channels = c(unique(dt.sampled$file_parent[dt.sampled$pol == 'r'])
                   , selected_channels_left)

dt.sampled_balanced = dt.sampled[file_parent %in% final_channels, ]
```

```{r}
#fix channel names
dt.sampled_balanced$channel_name = as.factor(dt.sampled_balanced$file_parent)
levels(dt.sampled_balanced$channel_name)[7:8] = c('thedailywire', 'rebelmedia')
```

Store final data
```{r}
#do not run
# save(dt.sampled_balanced
#      , file='../../../eurocss_ltta_workshop_data_sampled.RData')
```
-------